# Generated by Django 5.1.4 on 2025-01-06 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id_prediccion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_prediccion', models.DateTimeField(auto_now_add=True)),
                ('resultado_prediccion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('model_used', models.CharField(max_length=255)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('usuario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
