# Generated by Django 5.1.4 on 2025-07-25 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_config', models.CharField(max_length=100)),
                ('modo_crecimiento', models.CharField(choices=[('linear', 'Linear'), ('logistic', 'Logistic')], max_length=10)),
                ('capacidad_maxima', models.FloatField(blank=True, null=True)),
                ('intervalo_confianza', models.FloatField(default=0.8)),
                ('usar_est_anual', models.BooleanField(default=True)),
                ('fourier_anual', models.IntegerField(default=10)),
                ('usar_est_semanal', models.BooleanField(default=True)),
                ('fourier_semanal', models.IntegerField(default=3)),
                ('usar_est_diaria', models.BooleanField(default=False)),
                ('fourier_diaria', models.IntegerField(blank=True, null=True)),
                ('estacionalidad_modo', models.CharField(choices=[('additive', 'Aditiva'), ('multiplicative', 'Multiplicativa')], default='additive', max_length=15)),
                ('usar_feriados', models.BooleanField(default=False)),
                ('eventos_especiales', models.JSONField(default=list)),
                ('estacionalidades_personalizadas', models.JSONField(default=list)),
                ('regresores_adicionales', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePrediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha_predicha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prediccion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio_predicha', models.DateField()),
                ('fecha_fin_predicha', models.DateField()),
                ('cantidad_total_predicha', models.IntegerField()),
                ('resultado_prediccion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predicciones.configuracionmodelo')),
            ],
        ),
    ]
