# Generated by Django 5.1.4 on 2025-07-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id_prediccion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_prediccion', models.DateTimeField(auto_now_add=True)),
                ('resultado_prediccion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('model_used', models.CharField(max_length=255)),
            ],
        ),
    ]
