# Generated by Django 5.1.4 on 2025-08-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicciones', '0003_alter_prediccion_fecha_modificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionmodelo',
            name='capacidad_minima',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracionmodelo',
            name='changepoint_prior_scale',
            field=models.FloatField(default=0.05),
        ),
        migrations.AddField(
            model_name='configuracionmodelo',
            name='changepoints',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='configuracionmodelo',
            name='frecuencia_datos',
            field=models.CharField(choices=[('D', 'Diaria'), ('W', 'Semanal'), ('M', 'Mensual')], default='D', max_length=10),
        ),
        migrations.AddField(
            model_name='configuracionmodelo',
            name='holidays_prior_scale',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='configuracionmodelo',
            name='horizonte_cv',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='configuracionmodelo',
            name='incluir_incertidumbre_estacionalidad',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracionmodelo',
            name='incluir_incertidumbre_tendencia',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracionmodelo',
            name='n_changepoints',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='configuracionmodelo',
            name='periodo_cv',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='configuracionmodelo',
            name='seasonality_prior_scale',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='configuracionmodelo',
            name='usar_validacion_cruzada',
            field=models.BooleanField(default=False),
        ),
    ]
