# Generated by Django 5.1.4 on 2025-08-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicciones', '0004_configuracionmodelo_capacidad_minima_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleprediccion',
            old_name='id_prediccion',
            new_name='prediccion',
        ),
        migrations.AddField(
            model_name='configuracionmodelo',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción sencilla de para que sirve esta configuracion', null=True),
        ),
        migrations.AddField(
            model_name='configuracionmodelo',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
