# Generated by Django 5.1.4 on 2025-08-14 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicciones', '0005_rename_id_prediccion_detalleprediccion_prediccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionmodelo',
            name='horizonte_cv',
        ),
        migrations.RemoveField(
            model_name='configuracionmodelo',
            name='periodo_cv',
        ),
        migrations.RemoveField(
            model_name='configuracionmodelo',
            name='usar_validacion_cruzada',
        ),
        migrations.AddField(
            model_name='configuracionmodelo',
            name='tipo_dataset',
            field=models.CharField(choices=[('normal', 'Normal'), ('pocos_datos', 'Pocos Datos'), ('muchos_datos', 'Muchos Datos'), ('datos_ruidosos', 'Datos Ruidosos'), ('datos_huecos', 'Datos con Huecos')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='configuracionmodelo',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuracionmodelo',
            name='modo_crecimiento',
            field=models.CharField(choices=[('linear', 'Linear'), ('logistic', 'Logistic')], default='linear', max_length=10),
        ),
    ]
