# Generated by Django 5.1.4 on 2025-08-19 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predicciones', '0007_rename_fecha_predicha_detalleprediccion_fecha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracionmodelo',
            old_name='nombre',
            new_name='nombre_config',
        ),
    ]
