# Generated by Django 5.1.4 on 2025-08-19 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predicciones', '0008_rename_nombre_configuracionmodelo_nombre_config'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracionmodelo',
            old_name='nombre_config',
            new_name='nombre',
        ),
    ]
