# Generated by Django 5.1.4 on 2025-09-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicciones', '0009_rename_nombre_config_configuracionmodelo_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionmodelo',
            name='incertidumbre_muestras',
            field=models.PositiveIntegerField(default=1000, help_text='Número de muestras de incertidumbre'),
        ),
        migrations.AlterField(
            model_name='configuracionmodelo',
            name='crecimiento',
            field=models.CharField(choices=[('linear', 'Lineal'), ('logistic', 'Logístico')], default='linear', help_text='Tipo de crecimiento de la tendencia.', max_length=10),
        ),
        migrations.AlterField(
            model_name='configuracionmodelo',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción de la configuración', null=True),
        ),
        migrations.AlterField(
            model_name='configuracionmodelo',
            name='est_anual',
            field=models.BooleanField(default=True, help_text='Usar estacionalidad anual'),
        ),
        migrations.AlterField(
            model_name='configuracionmodelo',
            name='est_diaria',
            field=models.BooleanField(default=False, help_text='Usar estacionalidad diaria'),
        ),
        migrations.AlterField(
            model_name='configuracionmodelo',
            name='est_semanal',
            field=models.BooleanField(default=True, help_text='Usar estacionalidad semanal'),
        ),
        migrations.AlterField(
            model_name='configuracionmodelo',
            name='estacionalidades_extra',
            field=models.JSONField(default=list, help_text='Estacionalidades adicionales'),
        ),
        migrations.AlterField(
            model_name='configuracionmodelo',
            name='estado',
            field=models.BooleanField(default=True, help_text='Indica si la configuración está activa'),
        ),
        migrations.AlterField(
            model_name='configuracionmodelo',
            name='eventos',
            field=models.JSONField(default=list, help_text='Lista de eventos especiales'),
        ),
        migrations.AlterField(
            model_name='configuracionmodelo',
            name='fourier_anual',
            field=models.PositiveIntegerField(default=10, help_text='Complejidad Fourier anual'),
        ),
        migrations.AlterField(
            model_name='configuracionmodelo',
            name='fourier_diaria',
            field=models.PositiveIntegerField(blank=True, help_text='Complejidad Fourier diaria', null=True),
        ),
        migrations.AlterField(
            model_name='configuracionmodelo',
            name='fourier_semanal',
            field=models.PositiveIntegerField(default=3, help_text='Complejidad Fourier semanal'),
        ),
        migrations.AlterField(
            model_name='configuracionmodelo',
            name='inc_estacionalidad',
            field=models.BooleanField(default=True, help_text='Incluir incertidumbre en estacionalidad'),
        ),
        migrations.AlterField(
            model_name='configuracionmodelo',
            name='inc_tendencia',
            field=models.BooleanField(default=True, help_text='Incluir incertidumbre en tendencia'),
        ),
        migrations.AlterField(
            model_name='configuracionmodelo',
            name='modo_est',
            field=models.CharField(choices=[('additive', 'Aditiva'), ('multiplicative', 'Multiplicativa')], default='additive', help_text='Tipo de estacionalidad', max_length=15),
        ),
        migrations.AlterField(
            model_name='configuracionmodelo',
            name='n_cambios',
            field=models.PositiveIntegerField(default=25, help_text='Número de posibles puntos de cambio'),
        ),
        migrations.AlterField(
            model_name='configuracionmodelo',
            name='regresores',
            field=models.JSONField(default=list, help_text='Regresores externos'),
        ),
        migrations.AlterField(
            model_name='configuracionmodelo',
            name='scale_est',
            field=models.FloatField(default=10.0, help_text='Peso de la estacionalidad'),
        ),
        migrations.AlterField(
            model_name='configuracionmodelo',
            name='scale_feriados',
            field=models.FloatField(default=10.0, help_text='Peso de feriados/eventos'),
        ),
        migrations.AlterField(
            model_name='configuracionmodelo',
            name='usar_feriados',
            field=models.BooleanField(default=False, help_text='Usar feriados/eventos'),
        ),
    ]
