# Generated by Django 5.1.4 on 2025-10-17 21:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicciones', '0010_configuracionmodelo_incertidumbre_muestras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediccion',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
