# Generated by Django 5.1.4 on 2025-07-30 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteVenta',
            fields=[
                ('id_comprobante', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('numero_comprobante', models.CharField(max_length=20, unique=True)),
                ('metodo_pago', models.CharField(default='Efectivo', max_length=50)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comprobante', to='ventas.venta')),
            ],
        ),
        migrations.DeleteModel(
            name='FacturaVenta',
        ),
    ]
