# Generated by Django 5.1.4 on 2025-07-19 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='quiere_comprobante',
            field=models.BooleanField(default=False, help_text='Indica si el cliente quiere recibir factura por email'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_creacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_creado', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_modificado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='venta',
            name='id_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.cliente'),
        ),
        migrations.CreateModel(
            name='FacturaVenta',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('numero_factura', models.CharField(max_length=20, unique=True)),
                ('metodo_pago', models.CharField(default='Efectivo', max_length=50)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='ventas.venta')),
            ],
        ),
    ]
