# Generated by Django 5.1.4 on 2025-01-08 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0002_alter_movimiento_options'),
        ('ventas', '0002_remove_venta_estado_venta_alter_venta_fecha_venta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='id_tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.almacen'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(default='Efectivo', editable=False, max_length=50),
        ),
    ]
