# Generated by Django 5.1.4 on 2025-07-20 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0003_initial'),
        ('ventas', '0002_venta_quiere_comprobante_cliente_venta_id_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='id_producto',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='id_inventario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='almacenes.inventario'),
            preserve_default=False,
        ),
    ]
