# Generated by Django 5.1.4 on 2025-07-30 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_remove_cliente_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='fecha_venta',
        ),
    ]
