# Generated by Django 5.1.4 on 2025-08-20 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_rename_telefono_cliente_nit_ci_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobanteventa',
            name='comentario_modificacion',
        ),
        migrations.RemoveField(
            model_name='comprobanteventa',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='comprobanteventa',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='comprobanteventa',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='comprobanteventa',
            name='usuario_modificacion',
        ),
    ]
