# Generated by Django 5.1.4 on 2025-08-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_remove_comprobanteventa_comentario_modificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
