# Generated by Django 5.1.4 on 2025-10-17 21:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_detalleventa_sub_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
