# Generated by Django 5.1.4 on 2025-08-07 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0003_alter_almacen_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipomovimiento',
            old_name='naturelaza',
            new_name='naturaleza',
        ),
    ]
