# Generated by Django 5.1.4 on 2025-08-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0004_rename_naturelaza_tipomovimiento_naturaleza'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
