# Generated by Django 5.1.4 on 2025-08-12 00:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0005_inventario_estado'),
        ('productos', '0004_alter_categoria_nombre_alter_proveedor_marca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inventario',
            constraint=models.UniqueConstraint(fields=('producto', 'almacen'), name='unique_inventario'),
        ),
    ]
