# Generated by Django 5.1.4 on 2025-08-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0006_inventario_unique_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Cantidad de stock disponible', max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='stock_maximo',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Stock máximo', max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Stock mínimo', max_digits=10),
        ),
    ]
