# Generated by Django 5.1.4 on 2025-10-21 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0009_notificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='comentario_modificacion',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='usuario_modificacion',
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='inventario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventarios.inventario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('error', 'Error')], default='info', max_length=50),
        ),
    ]
