# Generated by Django 5.1.4 on 2025-08-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_categoria_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Marca'),
        ),
    ]
