# Generated by Django 5.1.4 on 2025-08-19 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_categoria_nombre_alter_proveedor_marca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='nombre_contacto',
            new_name='contacto',
        ),
    ]
