# Generated by Django 5.1.4 on 2025-05-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='productos/documentos/'),
        ),
    ]
