# Generated by Django 5.1.4 on 2025-09-29 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_rename_nombre_contacto_proveedor_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproducto',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='documento',
        ),
    ]
