# Generated by Django 5.1.4 on 2025-06-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_categoria_estado_categoria_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
