# Generated by Django 5.1.4 on 2025-07-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_solicitada', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRecepcion',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_recibida', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('recibido', 'Recibido')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecepcionPedido',
            fields=[
                ('id_recepcion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_recepcion', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('total_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_neto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
    ]
