# Generated by Django 5.1.4 on 2025-08-05 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.almacen'),
        ),
    ]
