# Generated by Django 5.1.4 on 2025-07-21 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0003_initial'),
        ('compras', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='id_tienda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='almacenes.almacen'),
            preserve_default=False,
        ),
    ]
