# Generated by Django 5.1.4 on 2025-08-02 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0003_remove_movimiento_id_usuario_and_more'),
        ('compras', '0003_remove_compra_fecha_compra_remove_compra_id_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.inventario'),
        ),
    ]
