# Generated by Django 5.1.4 on 2025-07-22 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_compra_id_tienda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='usuario',
            new_name='id_usuario',
        ),
    ]
