# Generated by Django 5.1.4 on 2025-08-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha_modificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_modificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
