# Generated by Django 5.1.4 on 2025-08-08 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_alter_compra_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='almacen',
        ),
    ]
