# Generated by Django 5.1.4 on 2025-07-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_rename_total_bruto_compra_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha_recepcion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
