# Generated by Django 5.1.4 on 2025-08-09 16:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_remove_compra_almacen'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='nro_factura',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='razon_social',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='subtotal_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cancelado', 'Cancelado'), ('Completado', 'Completado')], default='Pendiente', max_length=20),
        ),
    ]
