# Generated by Django 5.1.4 on 2025-08-10 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_compra_nro_factura_compra_razon_social_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallepedido',
            old_name='cantidad_solicitada',
            new_name='cantidad',
        ),
    ]
