# Generated by Django 5.1.4 on 2025-08-10 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_rename_cantidad_solicitada_detallepedido_cantidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallepedido',
            old_name='cantidad',
            new_name='cantidad_solicitada',
        ),
    ]
