# Generated by Django 5.1.4 on 2025-08-10 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_rename_cantidad_detallepedido_cantidad_solicitada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallepedido',
            old_name='inventario',
            new_name='producto',
        ),
    ]
