# Generated by Django 5.1.4 on 2025-08-20 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_rename_inventario_detallepedido_producto'),
        ('inventarios', '0007_alter_inventario_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='almacen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventarios.almacen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='almacen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventarios.almacen'),
            preserve_default=False,
        ),
    ]
