# Generated by Django 5.1.4 on 2025-09-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0011_alter_pedido_fecha_entrega_alter_pedido_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
