# Generated by Django 5.1.4 on 2025-09-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0012_alter_pedido_fecha_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
