# Generated by Django 5.1.4 on 2025-09-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0013_alter_detallecompra_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cancelado', 'Cancelado'), ('Recepcionado', 'Recepcionado')], default='Pendiente', max_length=20),
        ),
    ]
