# Generated by Django 5.1.4 on 2025-10-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0014_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='nro_factura',
            field=models.CharField(max_length=50),
        ),
    ]
