# Generated by Django 5.1.3 on 2024-12-30 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlmacenOTienda',
            fields=[
                ('id_almacen_o_tienda', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('stock_minimo', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('comentario_modificacion', models.TextField(blank=True, null=True)),
                ('almacen_o_tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.almacenotienda')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('usuario_creacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios_creados', to='usuarios.user')),
                ('usuario_modificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios_modificados', to='usuarios.user')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad__gte', 0)), name='cantidad_no_negativa'), models.CheckConstraint(condition=models.Q(('stock_minimo__gte', 0)), name='stock_minimo_no_negativo')],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_entrada', to='almacenes.almacenotienda')),
                ('origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_salida', to='almacenes.almacenotienda')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.user')),
                ('tipo_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.tipomovimiento')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad__gte', 0)), name='movimiento_cantidad_no_negativa')],
            },
        ),
    ]
