# Generated by Django 5.1.4 on 2025-01-07 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimiento',
            options={},
        ),
    ]
