# Generated by Django 5.1.4 on 2025-07-30 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='comentario_modificacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='usuario_creacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='usuario_modificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='usuario_creacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='usuario_modificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='usuario_creacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='usuario_modificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL),
        ),
    ]
