# Generated by Django 5.1.4 on 2025-07-20 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='id_almacen',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='id_producto',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='id_inventario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='almacenes.inventario'),
            preserve_default=False,
        ),
    ]
