# Generated by Django 5.1.4 on 2025-07-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0004_remove_movimiento_id_almacen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='cantidad',
            field=models.IntegerField(help_text='Cantidad del movimiento. Siempre positiva. La naturaleza define si es entrada o salida.'),
        ),
    ]
